# Generated by Django 2.2.2 on 2019-07-01 07:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('userprofile', '0001_initial'),
        ('courses', '0015_auto_20190620_1306'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuestionSet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('passingscore', models.PositiveSmallIntegerField(default=1, verbose_name='passing score')),
                ('maxscore', models.PositiveSmallIntegerField(default=1, verbose_name='max score')),
                ('maxattempt', models.PositiveSmallIntegerField(default=1, verbose_name='max attempt')),
                ('updated_on', models.DateTimeField(auto_now=True, verbose_name='last updated')),
                ('cs_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='courses.CourseSet')),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prompt', models.TextField(max_length=1000, verbose_name='question prompt')),
                ('questionscore', models.PositiveSmallIntegerField(default=1, verbose_name='question score')),
                ('questionorder', models.PositiveSmallIntegerField(verbose_name='question order')),
                ('questionset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quizdown.QuestionSet')),
            ],
        ),
        migrations.CreateModel(
            name='Choice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(help_text='Pick this choice?', max_length=1000)),
                ('correct', models.BooleanField(default=False, help_text='Is this the right answer?')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quizdown.Question')),
            ],
            options={
                'verbose_name': 'Answer',
                'verbose_name_plural': 'Answers',
            },
        ),
        migrations.CreateModel(
            name='UserQuizSubmission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_submission_on', models.DateTimeField(auto_now=True, verbose_name='last updated')),
                ('usermaxscore', models.PositiveSmallIntegerField(default=0, verbose_name='user max score')),
                ('userattempt', models.PositiveSmallIntegerField(default=0, verbose_name='user attempt')),
                ('questionset', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='quizdown.QuestionSet')),
                ('userprofile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submitted_by', to='userprofile.UserProfile')),
            ],
            options={
                'verbose_name': 'Question',
                'verbose_name_plural': 'Questions',
                'unique_together': {('questionset', 'userprofile')},
            },
        ),
    ]
