# Generated by Django 2.2.2 on 2019-07-01 08:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quizdown', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='questionset',
            old_name='cs_id',
            new_name='cs',
        ),
    ]
