# Generated by Django 2.2.2 on 2019-07-05 12:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quizdown', '0002_auto_20190701_1511'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='questionorder',
        ),
    ]
