# Generated by Django 2.2.1 on 2019-05-18 10:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CourseSet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('repo_url', models.URLField(verbose_name='repo url')),
                ('created_on', models.DateTimeField(verbose_name='created on')),
                ('owner', models.SlugField(verbose_name='owner')),
                ('favorite_n', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(verbose_name='created on')),
                ('last_updated', models.DateTimeField(verbose_name='last updated')),
                ('favorite_n', models.IntegerField(default=0)),
                ('comments_n', models.IntegerField(default=0)),
                ('course_url', models.URLField(verbose_name='course url')),
                ('courseset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.CourseSet')),
            ],
        ),
    ]
