# Generated by Django 2.2.1 on 2019-05-21 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='courseset',
            name='updated_on',
            field=models.DateTimeField(default=None, verbose_name='last updated'),
            preserve_default=False,
        ),
    ]
