# Generated by Django 2.2.1 on 2019-05-23 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_auto_20190523_1634'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courseset',
            name='created_on',
            field=models.DateTimeField(auto_now_add=True, verbose_name='created on'),
        ),
        migrations.AlterField(
            model_name='courseset',
            name='updated_on',
            field=models.DateTimeField(auto_now=True, verbose_name='last updated'),
        ),
    ]
