# Generated by Django 2.2.1 on 2019-05-23 12:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('courses', '0005_auto_20190523_1821'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApprovalQueue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('repo_url', models.URLField(verbose_name='repo url')),
                ('submitted_on', models.DateTimeField(auto_now_add=True, verbose_name='submitted on')),
                ('approved_status', models.BooleanField(default=False, verbose_name='approved status')),
                ('approved_by_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='courseset',
            name='approved_by',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='courses.ApprovalQueue'),
        ),
    ]
