# Generated by Django 2.2.1 on 2019-05-23 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0006_auto_20190523_1941'),
    ]

    operations = [
        migrations.AlterField(
            model_name='approvalqueue',
            name='repo_url',
            field=models.URLField(unique=True, verbose_name='repo url'),
        ),
        migrations.AlterField(
            model_name='courseset',
            name='repo_url',
            field=models.URLField(unique=True, verbose_name='repo url'),
        ),
    ]
