# Generated by Django 2.2.1 on 2019-05-24 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0008_auto_20190523_2027'),
    ]

    operations = [
        migrations.AlterField(
            model_name='approvalqueue',
            name='repo_url',
            field=models.SlugField(verbose_name='repo url'),
        ),
    ]
