# Generated by Django 2.2.1 on 2019-05-24 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0009_auto_20190524_1624'),
    ]

    operations = [
        migrations.AlterField(
            model_name='approvalqueue',
            name='repo_url',
            field=models.SlugField(unique=True, verbose_name='repo slug'),
        ),
        migrations.AlterField(
            model_name='courseset',
            name='repo_url',
            field=models.SlugField(unique=True, verbose_name='repo slug'),
        ),
    ]
