# Generated by Django 2.2.1 on 2019-06-04 06:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('courses', '0010_auto_20190524_1757'),
    ]

    operations = [
        migrations.AddField(
            model_name='approvalqueue',
            name='submitted_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='discovered', to=settings.AUTH_USER_MODEL),
        ),
    ]
