# Generated by Django 2.2.1 on 2019-05-24 11:05

import courses.forms
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0010_auto_20190524_1757'),
    ]

    operations = [
        migrations.AlterField(
            model_name='approvalqueue',
            name='repo_url',
            field=models.SlugField(unique=True, validators=[courses.forms.validate_repo_url], verbose_name='repo slug'),
        ),
        migrations.AlterField(
            model_name='courseset',
            name='repo_url',
            field=models.SlugField(unique=True, validators=[courses.forms.validate_repo_url], verbose_name='repo slug'),
        ),
    ]
