# Generated by Django 2.2.1 on 2019-06-08 06:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0013_auto_20190608_1354'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='approvalqueue',
            options={'permissions': [('approve_course', 'Can approve a course submitted to the Queue by setting status as True'), ('remove_course', 'Can remove a course from the Queue by setting status as False')]},
        ),
    ]
