# Generated by Django 2.2.2 on 2019-07-03 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0015_auto_20190620_1306'),
    ]

    operations = [
        migrations.AddField(
            model_name='courseset',
            name='quizcontent',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
